---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: mapserver
          image: liguriadigitale/mapserver
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: mapserver
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 8082
status:
  loadBalancer: {}
---
