version: '2'
networks:
  default:
    driver: bridge
services:
  libpostal:
    image: pelias/libpostal-service
    container_name: pelias_libpostal
    user: "1000"
    restart: always
    ports: [ "4400:4400" ]
  schema:
    image: pelias/schema:master
    container_name: pelias_schema
    user: "1000"
    volumes:
      - "./pelias.json:/code/pelias.json"
  api:
    image: pelias/api:master
    container_name: pelias_api
    user: "1000"
    restart: always
    environment: [ "PORT=4000" ]
    ports: [ "4000:4000" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
  placeholder:
    image: pelias/placeholder:master
    container_name: pelias_placeholder
    user: "1000"
    restart: "no"
    environment: [ "PORT=4100" ]
    ports: [ "4100:4100" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "/data/pelias/liguria/:/data"
      - "./blacklist/:/data/blacklist"
  whosonfirst:
    image: pelias/whosonfirst:master
    container_name: pelias_whosonfirst
    user: "1000"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "/data/pelias/liguria/:/data"
      - "./blacklist/:/data/blacklist"
  openstreetmap:
    image: pelias/openstreetmap:master
    container_name: pelias_openstreetmap
    user: "1000"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "/data/pelias/liguria/:/data"
      - "./blacklist/:/data/blacklist"
  openaddresses:
    image: pelias/openaddresses:master
    container_name: pelias_openaddresses
    user: "1000"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "/data/pelias/liguria/:/data"
      - "./blacklist/:/data/blacklist"
  transit:
    image: pelias/transit:master
    container_name: pelias_transit
    user: "1000"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "/data/pelias/liguria/:/data"
  csv-importer:
    image: pelias/csv-importer:master
    container_name: pelias_csv_importer
    user: "1000"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "/data/pelias/liguria/:/data"
      - "./blacklist/:/data/blacklist"
  polylines:
    image: pelias/polylines:master
    container_name: pelias_polylines
    user: "1000"
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "/data/pelias/liguria/:/data"
  interpolation:
    image: pelias/interpolation:master
    container_name: pelias_interpolation
    user: "1000"
    restart: always
    environment: [ "PORT=4300" ]
    ports: [ "4300:4300" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "/data/pelias/liguria/:/data"
  pip:
    image: pelias/pip-service:master
    container_name: pelias_pip-service
    user: "1000"
    restart: always
    environment: [ "PORT=4200" ]
    ports: [ "4200:4200" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "/data/pelias/liguria/:/data"
  elasticsearch:
    image: pelias/elasticsearch:7.5.1
    #image: registry:5000/pelias-elastic
    container_name: pelias_elasticsearch
    user: "1000"
    restart: unless-stopped
    ports: [ "9200:9200", "9300:9300" ]
    volumes:
      - "/data/pelias/liguria/elasticsearch:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: [ "IPC_LOCK" ]
