apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --volumes hostPath --file docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --volumes hostPath --file docker-compose.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - image: pelias/elasticsearch:7.5.1
        imagePullPolicy: ""
        name: pelias-elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources: {}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
          runAsUser: 1000
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-hostpath0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /data/pelias/liguria/elasticsearch
        name: elasticsearch-hostpath0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --volumes hostPath --file docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  type: LoadBalancer
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
    nodePort: 9200
  - name: "9300"
    port: 9300
    targetPort: 9300
    nodePort: 9300
  selector:
    io.kompose.service: elasticsearch
status:
  loadBalancer: {}
---
