apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --volumes hostPath --file docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: openstreetmap
  name: openstreetmap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openstreetmap
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --volumes hostPath --file docker-compose.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: openstreetmap
    spec:
      containers:
      - image: pelias/openstreetmap:master
        imagePullPolicy: ""
        name: pelias-openstreetmap
        resources: {}
        securityContext:
          runAsUser: 1000
        volumeMounts:
        - mountPath: /code/pelias.json
          name: openstreetmap-hostpath0
        - mountPath: /data
          name: openstreetmap-hostpath1
        - mountPath: /data/blacklist
          name: openstreetmap-hostpath2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /otp/geocoder/docker/projects/liguria/pelias.json
        name: openstreetmap-hostpath0
      - hostPath:
          path: /data/pelias/liguria/
        name: openstreetmap-hostpath1
      - hostPath:
          path: /otp/geocoder/docker/projects/liguria/blacklist
        name: openstreetmap-hostpath2
status: {}
