---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uiliguria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: uiliguria
          image: liguriadigitale/travelplanner-ui-liguria:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
          - name: CONFIG
            value: "kuopio"
---
apiVersion: v1
kind: Service
metadata:
  name: uiliguria
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 8088
status:
  loadBalancer: {}
---
