apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mobimart-liguria.com
  - http:
      paths:
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: ui
            port:
              number: 8086
