apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - my-asn: 64500
      peer-asn: 64500
      peer-address: 10.11.6.189
    address-pools:
    - name: ip-mobimart
      protocol: bgp
      addresses:
      - 10.11.6.189
